
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqjplglnlhrndlpvxwgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxanBsZ2xubGhybmRscHZ4d2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NDI3NDUsImV4cCI6MjA1ODMxODc0NX0.Zg-Mo5HE_zfWZJWqRdcBF3QEAatTp3OJfKnB7PPAFyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});

// Log initialization for debugging
console.log('Supabase client initialized with URL:', SUPABASE_URL);
